### ISSUE TITLE
Combine the splash page with the next-auth signIn page

### ISSUE THREAD

**Issue by koltclassic** [GuthrieW/dotts-trading-cards-version-2#19]
https://next-auth.js.org/configuration/pages#examples

We might be able to condense going from splash page -> log in with google -> google login -> home page.

I think if we use the `signIn` option inside of the `pages` property on the nextauth file we can simplify things to splash page  -> google login -> home page.

If we support multiple logins in the future the splash page "Log In" button could open a modal to select provider options.

**Comment by GuthrieW** [comment]
This is no longer a valid issue because we are not using next-auth anymore.
