### ISSUE TITLE
Add descriptive password requirements

### ISSUE THREAD

**Issue by GuthrieW** [GuthrieW/dotts-trading-cards-version-2#29]
When a password is not strong enough in the sign up page we should tell the user the password's minimum requirements.

<img width="861" alt="Screen Shot 2021-02-04 at 3 32 00 PM" src="https://user-images.githubusercontent.com/18729387/106958128-8e4bf100-66fe-11eb-8da2-7472de0200aa.png">

**Comment by koltclassic** [comment]
fixed with https://github.com/GuthrieW/dotts-trading-cards-version-2/pull/58
